### ISSUE TITLE
warning stops me from saving valid changes

### ISSUE THREAD

**Issue by WhiteG00se** [Synthlight/RE-Editor#10]
Hi there,

I'm trying to edit ShopDisplayData.user.2
If I edit a value in the Id column, it shows an "!" and doesn't let me save these changes.
![image](https://github.com/Synthlight/MHR-Editor/assets/17803402/d2cc0c68-8ed3-4de1-8b5d-9d64125b41c3)
At first I thought this is because it would cause issues if I changed the value.
But I did some testing with a hex editor, and if I change it e.g. to 0x4100005 I get a max potion in the shop (by default it's 0x4100009 which is life powder) and everything works just fine.

I'd much rather use the editor than fiddle with a hex editor.
Is there a good reason why you prevent users from saving these changes, that I'm not seeing?
If not, could you please change that?

BR
Tobi

**Comment by Synthlight** [comment]
Please include the FULL path to the file in natives. The name isn't always unique, and with the full path I don't have to hunt/search for it.
The full path also tells me if you're on STM or MSG which is need to know information.
I'm going to assume you're talking about this file: `natives\STM\data\Facility\ItemShop\VillageShop\ShopDisplayData.user.2`

Unable to replicate with the latest build.
You aren't even supposed to enter numbers directly there. You MUST select an entry from the item DDL, which might not be appearing on the public release.
I've done a lot of work under the hood since the last release, so it's probably better to just release a new version since I have no idea what your issue is nor are able to replicate it.

But the `!` just means one of the fields has illegal data. That is not the error. The red box being on the _edited ID_ is the error, and it indicates that you're entering a value that isn't valid for the field.
The row will not commit changes done to it till the incorrect values are corrected.

**Comment by WhiteG00se** [comment]
`natives\STM\data\Facility\ItemShop\VillageShop\ShopDisplayData.user.2` is indeed the correct path.
I just tested v1.5 (btw. windows defender complains about it be virus) and yes, there is a massive difference:

![image](https://github.com/Synthlight/MHR-Editor/assets/17803402/4e3cc13f-e079-48f3-b088-15609c279f75)

Thanks for the new release. The problem is resolved now. If only I had asked you 2 days earlier, I'd have saved myself from a lot of fiddling 😄
