### ISSUE TITLE
'Type Cannot be Inferred' problem in reading DD2 official data file

### ISSUE THREAD

**Issue by MooGuZ** [Synthlight/RE-Editor#12]
When I tried to open 'gm80_001_gmdata.user.2'([RE Data File.zip](https://github.com/user-attachments/files/17439412/RE.Data.File.zip)), which is the official file for loot information in wild with latest version (1.1.7.0). Following error comes out:

```
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: The type arguments for method 'RE_Editor.Windows.MainWindow.MakeDataGrid<T>(System.Collections.Generic.IList<T>, RE_Editor.Common.Models.RSZ, System.Collections.Generic.IList<T>)' cannot be inferred from the usage. Try specifying the type arguments explicitly.

   at CallSite.Target(Closure , CallSite , MainWindow , Object , RSZ , Object )

   at System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)

   at RE_Editor.Windows.MainWindow.Load(String filePath) in R:\Code\RE-Editor\RE-Editor\Windows\MainWindow.xaml.cs:line 209
```

I have checked older versions and find this problem is introduced by 1.1.5.0. 1.1.4.0 can open the file successfully.

**Comment by Synthlight** [comment]
There's a lot of files that start with generic lists, like this one. The actual wrapper object is `App_GimmickParamBase` and, in this case, the contents are `App_Gm80_001Param` which inherits from base.
This has been one headache after another. I have to do crazy things to get it to show as the derived class, which was needed since the base class of whatever I was fixing this for in 1.1.5.0 had like no fields.

Bottom line, I need to implement a much better system for this, but for now, use this version. It at least fixes this file, and I'll work on implementing a better system and actual tests for the rest.

(No version change as it's not an official release.)

PS: Adding the file is good, but please tell me the **path** to it in the future. I'm assuming you mean `natives/STM/AppSystem/Gimmick/UserData/gm80_001_gmdata.user.2`.

[DD2-Release.zip](https://github.com/user-attachments/files/17446668/DD2-Release.zip)

**Comment by MooGuZ** [comment]
Thanks for the hotfix.

PS: `natives/STM/AppSystem/Gimmick/UserData/gm80_001_gmdata.user.2` is the correct path.

**Comment by Synthlight** [comment]
Fixed in the code now, I'll make releases eventually.
