### ISSUE TITLE
Sunbreak Support?

### ISSUE THREAD

**Issue by Thorbenl** [Synthlight/RE-Editor#2]
Any desire to support sunbreak? :)

**Comment by Synthlight** [comment]
I've already been working on the new string mess they made since like an hour after release. SB fucked shit up and now that praydog sent me the data dumps I can at least open the data files and start comparing things to in-game values to make sure the string are right.

They basically put the MR texts in a separate files **using the same exact fucking ids**. \*sigh\*

I've got it working for items but am at work and may not be done till tomorrow.
